---
version: '3'
services:
  frontend:
    container_name: frontend
    image: "cr.tik.uni-stuttgart.de/izus-darus/license-checker/frontend:${TAGFRONTED}"
    ports:
      - '5173:80'
    networks:
      - resus
    restart: unless-stopped
  backend:
    container_name: backend
    image: "cr.tik.uni-stuttgart.de/izus-darus/license-checker/backend:${TAGBACKEND}"
    ports:
      - '8000:8000'
    networks:
      - resus
    restart: unless-stopped
  fossology:
    container_name: fossology
    image: docker.io/fossology/fossology:4.6.0
    platform: linux/amd64
    ports:
      - '7100:7100'
    networks:
      - resus
    restart: unless-stopped
  license-engine:
    container_name: engine
    image: "cr.tik.uni-stuttgart.de/izus-darus/license-checker/engine:${TAGENGINE}"
    ports:
      - '7001:7000'
    networks:
      - resus
    environment:
      - FOSSOLOGY_ENDPOINT_BASE_PATH=http://fossology:80
    restart: unless-stopped
networks:
  resus:
    driver: bridge
